version: "2.0"
services:
  node-1:
    build: ../../
    image: cbainnovationlab/quorum
    ports:
      - "8545:8545"
    volumes:
      - ./node1:/root/quorum
    networks:
      main:
        ipv4_address: 172.16.238.2
        aliases:
          - node-1
  node-2:
    build: ../../
    image: cbainnovationlab/quorum
    volumes:
      - ./node2:/root/quorum
    networks:
      main:
        ipv4_address: 172.16.238.3
        aliases:
          - node-2
  node-3:
    build: ../../
    image: cbainnovationlab/quorum
    volumes:
      - ./node3:/root/quorum
    networks:
      main:
        ipv4_address: 172.16.238.4
        aliases:
          - node-3
  node-4:
    build: ../../
    image: cbainnovationlab/quorum
    volumes:
      - ./node4:/root/quorum
    networks:
      main:
        ipv4_address: 172.16.238.5
        aliases:
          - node-4
  node-5:
    build: ../../
    image: cbainnovationlab/quorum
    volumes:
      - ./node5:/root/quorum
    networks:
      main:
        ipv4_address: 172.16.238.6
        aliases:
          - node-5
  node-6:
    build: ../../
    image: cbainnovationlab/quorum
    volumes:
      - ./node6:/root/quorum
    networks:
      main:
        ipv4_address: 172.16.238.7
        aliases:
          - node-6
  node-7:
    build: ../../
    image: cbainnovationlab/quorum
    volumes:
      - ./node7:/root/quorum
    networks:
      main:
        ipv4_address: 172.16.238.8
        aliases:
          - node-7
networks:
  main:
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24